language: haskell
ghc:
  - 7.8
  - 7.6
branches:
  only:
    - master
    - travis

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libwebkitgtk-dev
  - cabal install cabal-install
  - cabal install alex happy
  - cabal install gtk2hs-buildtools
  - git clone https://github.com/pavelkogan/reactive-banana-gtk.git
  - cabal sandbox init
  - cabal sandbox add-source ./reactive-banana-gtk/

