env:
  - CABALVER=1.18 GHCVER=7.8.4 LTSVER=2.5 ALEXVER=3.1.4 HAPPYVER=1.19.5
sudo: false
branches:
  only:
    - master
    - travis
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - libwebkitgtk-dev
      - ghc-7.8.4
      - cabal-install-1.18
      - alex-3.1.4
      - happy-1.19.5

before_install:
  - env
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$PATH
  - travis_retry cabal update
  - travis_retry wget http://www.stackage.org/lts/$LTSVER/cabal.config
  - cabal sandbox init --sandbox $HOME/cabal.sandbox
  - export PATH=$HOME/cabal.sandbox/bin:$PATH
  - gtk2hsC2hs -v || cabal install gtk2hs-buildtools
  - git clone https://github.com/pavelkogan/reactive-banana-gtk.git
  - cabal sandbox add-source ./reactive-banana-gtk/

install:
  - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks -v2 --prefix=/usr/local
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist

cache:
  directories:
    - $HOME/cabal.sandbox

before_deploy:
  - cabal copy --destdir=dist/image
  - tar czvf $TRAVIS_TAG.tar.gz -C dist/image usr
deploy:
  provider: releases
  api_key:
    secure: Qm2v/za78wzzXqjPWBE00mQQ2EYoekummmF/Ix2pR/APxI1H1MzM7DWaTZGFKDFOg/Lt4AVa5RXSYtgRpzpUgsT74KXe6cs+biX6WbO+5kNyRkYTv7f485yXbCJdbqgn9Rk65SDfPLbJmVZkUVY4u7fa+jlPMikkYd7BeaCTVf0=
  file: $TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    all_branches: true
