env:
  - CABALVER=1.18 GHCVER=7.8.4 LTSVER=2.5 ALEXVER=3.1.4 HAPPYVER=1.19.5
sudo: false
branches:
  only:
    - master
    - travis
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - libwebkitgtk-dev
      - ghc-7.8.4
      - cabal-install-1.18
      - alex-3.1.4
      - happy-1.19.5

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$PATH
  - travis_retry cabal update
  - travis_retry wget http://www.stackage.org/lts/$LTSVER/cabal.config
  - cabal sandbox init --sandbox $HOME/cabal.sandbox
  - export PATH=$HOME/cabal-sandbox/bin:$PATH
  - cabal install gtk2hs-buildtools
  - git clone https://github.com/pavelkogan/reactive-banana-gtk.git
  - cabal sandbox add-source ./reactive-banana-gtk/

install:
  - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks -v2
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist

cache:
  directories:
    - $HOME/cabal.sandbox
