language: haskell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libglib2.0-dev libcairo2-dev libpango1.0-dev libgtk2.0-dev
  - git clone https://github.com/pavelkogan/reactive-banana-gtk.git
  - cabal sandbox init
  - cabal sandbox add-source ./reactive-banana-gtk/

