language: haskell
ghc: 7.8
env:
  - LTS_VER=2.5
sudo: false
branches:
  only:
    - master
    - travis
addons:
  apt:
    packages:
      - libwebkitgtk-dev

before_install:
  - cabal update
  - cabal install stackage-cli gtk2hs-buildtools
  - stackage-sandbox init lts-$LTS_VER
  - git clone https://github.com/pavelkogan/reactive-banana-gtk.git
  - cabal sandbox add-source ./reactive-banana-gtk/

cache:
  directories:
    - $HOME/.stackage/sandboxes
